### ISSUE TITLE
proc with newline in body

### ISSUE THREAD

**Issue by enthus1ast** [piotrklibert/nimiTCL#1]
```
# I'm not familiar with tcl so this maybe just noise ;)

# Works
proc f {a} {echo $a}
f "Calling a command"

# Works NOT
proc f {a} {
    echo $a
}
f "Calling a command"
```

**Comment by piotrklibert** [comment]
Oh shit! Checking right now, thanks @enthus1ast!

**Comment by piotrklibert** [comment]
Ok, fixed! I also implemented a REPL and added a few more examples to the test string in `src/main.nim`. And also, calls to user-defined (via `proc`) commands no longer overwrite the values in the global scope which have the same names as command formal args. And we're still at 275 loc! ;)
